const String participantsCollection = "participants";

List<String> listCities = [
  'Agadir',
  'Ait Melloul',
  'Anza',
  'Azrou',
  'Biougra',
  'Belfaa',
  'Beni Mellal',
  'Chtouka Aitbaha',
  'Drarga',
  'El Kolea',
  'Essaouira',
  'Essmara',
  'Inzegan',
  'Laayoune',
  'Ouled Teima',
  'Rabat',
  'Sale',
  'Taroudant',
  'Temsia',
  'Tikiouine',
  'Tiiznit',
];
