// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_3xigAcbM7q1OTHsFEvrLou2G5Ni23g',
    appId: '1:803356594392:web:b234c79a699d22802e47ad',
    messagingSenderId: '803356594392',
    projectId: 'halem-devloper',
    authDomain: 'halem-devloper.firebaseapp.com',
    storageBucket: 'halem-devloper.appspot.com',
    measurementId: 'G-X7HBCBGQYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDns4x8UjcPZR0EsMFdQNW6i-KMPklVVog',
    appId: '1:803356594392:android:85d20f63a681494d2e47ad',
    messagingSenderId: '803356594392',
    projectId: 'halem-devloper',
    storageBucket: 'halem-devloper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF6UcS9ND-XSkQGIDEQYXOQLLvIOns6dA',
    appId: '1:803356594392:ios:f2abc6e885b3f3522e47ad',
    messagingSenderId: '803356594392',
    projectId: 'halem-devloper',
    storageBucket: 'halem-devloper.appspot.com',
    iosClientId: '803356594392-lg3i05kvr9t0o6omk2da29rk848te730.apps.googleusercontent.com',
    iosBundleId: 'com.nokhba.center.centerManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF6UcS9ND-XSkQGIDEQYXOQLLvIOns6dA',
    appId: '1:803356594392:ios:f2abc6e885b3f3522e47ad',
    messagingSenderId: '803356594392',
    projectId: 'halem-devloper',
    storageBucket: 'halem-devloper.appspot.com',
    iosClientId: '803356594392-lg3i05kvr9t0o6omk2da29rk848te730.apps.googleusercontent.com',
    iosBundleId: 'com.nokhba.center.centerManager',
  );
}
